### ISSUE TITLE
Stats service is never running

### ISSUE THREAD

**Issue by vipinjn24** [GriffinPlus/docker-zimbra#12]
Hi,

Stats service is never running in the server with kubernetes deployment.

Kindly let me know where to check for the issue.

![image](https://user-images.githubusercontent.com/1639185/98770016-466f4380-2407-11eb-9c98-eeca77ac9b48.png)
Thanks

**Comment by ravenpride** [comment]
Hi @vipinjn24,

the *stats* service is a tiny beast that sometimes causes issues. These issues are most likely related to the Zimbra installation itself. Does [this](https://forums.zimbra.org/viewtopic.php?t=65513) help you to get rid of it? I had problems with this service as well, but most of the time simply waiting a few minutes let it get checked green in the list.

**Comment by vipinjn24** [comment]
Hmm i tried this and waited for so long but nothing happened.

**Comment by ravenpride** [comment]
Hm, I'm afraid the only thing you could do in this case is to exec into the container and examine the logs.

**Comment by loopold** [comment]
Hi. If I could trust my notes I changed in `/opt/zimbra/libexec/zmstat-ldap` lines 96 and 102:
```sh
my $pass = qx(zmlocalconfig -m nokey -s zimbra_ldap_password);
```
with absolute path `/opt/zimbra/bin/zmlocalconfig` and that solved my problem with not running `stats`

**Comment by ravenpride** [comment]
Hello @loopold, thank you for the hint. If this really works, it seems to be an issue with the `PATH` variable, although the container simply sets up an Ubuntu environment and installs Zimbra right on top of it, so the container itself does not juggle around with the `PATH` variable. I'm sorry, but I cannot verify this as I've migrated my mail system to Mailcow - no Zimbra on my side any more :-|

**Comment by vipinjn24** [comment]
@loopold You are an angel. :)
This fixed the issue. thanks.

**Comment by ravenpride** [comment]
Thank you for your help, @loopold. I'll close the issue, please feel free to reopen it, if needed.
