### ISSUE TITLE
zmdhparam: ERROR: no zimbraSSLDHParam in openssl

### ISSUE THREAD

**Issue by kevintvh** [GriffinPlus/docker-zimbra#14]
Hi,
Follow the steps to run the ./run.sh and getting below error:

```
Adding Zimbra's Perl include path to search path...

Generating stronger DH parameters (4096 bit)...
Generating DH parameters, 4096 bit long safe prime, generator 2
This is going to take a long time
.......................................................................................................................................................................................................................+...................++*++*++*
zmdhparam: ERROR: no zimbraSSLDHParam in openssl
```
I've done this twice after the full clean up.
Please advise. 

Thanks,
Kevin.

**Comment by ravenpride** [comment]
Hi @kevintvh,

this error is a bit strange as the following line generates it:

https://github.com/GriffinPlus/docker-zimbra/blob/bc4efe841152e1ecfb37d333f969df69f3868df9/target/app/install-zimbra.sh#L88

This line only calls one of zimbra's own tools.

I've tested the shipped version of Zimbra with Ubuntu 18.04 LTS and it worked at the time I've set it up. As the version of Zimbra did not change, the only thing I can imagine is that there is something wrong with the Ubuntu installation. Can you please delete the docker volume mounted into the zimbra container and try again? Perhaps there is something wrong with the bootstrapping process.

**Comment by kevintvh** [comment]
Hi @ravenpride,
Thank you for your response.

Yes, I did clean up everything and try it again but same error in this phase only.
Can you run this in your machine to see if it works in your machine with current code base ?

Thanks,
Kevin.

**Comment by ravenpride** [comment]
Hi @kevintvh,

I've freshly installed a Ubuntu 20.04 LTS Server on a virtual machine and gave it a try. I could reproduce the issue and I've found the line in `/opt/zimbra/bin/zmdhparam` where the error occurs. `zimbraSSLDHParam` is an LDAP attribute storing the DH params in PEM format. And this attribute seems to be unset. Therefore this seems to be a Zimbra issue we cannot fix directly. The only thing we can do is to comment out this line

https://github.com/GriffinPlus/docker-zimbra/blob/bc4efe841152e1ecfb37d333f969df69f3868df9/target/app/install-zimbra.sh#L88
