### ISSUE TITLE
Faied on chroot /data mount -t proc proc /proc#015

### ISSUE THREAD

**Issue by Phil67ago** [GriffinPlus/docker-zimbra#5]
Can't get the container up and running.
Get error at chroot....

My commands:
mkdir /voldata

docker volume create --name zimbra-data --opt type=none --opt device=/voldata --opt o=bind

docker run -it --rm --network bridge --name "zimbra" --hostname zimbra.server.com -p 192.168.0.170:443:443 --volume zimbra-data:/data:z --cap-add NET_ADMIN --cap-add SYS_ADMIN --cap-add SYS_PTRACE --security-opt apparmor=unconfined griffinplus/zimbra run-and-enter

host: /var/log/messages
Jan 10 21:29:08 host ...: W: Failure trying to run: chroot /data mount -t proc proc /proc#015

Error only once, then I have to purn the container and start again.
I think its due here:
https://github.com/GriffinPlus/docker-zimbra/blob/master/target/docker-entrypoint.sh : 40 function setup_environment

Some more info:
It is selinux causing the error in debootstrap.log
mount: /proc: cannot mount proc read-only.

avc:  denied  { mount } for  ....name="/" dev="proc" ino=1 
scontext=system_u:system_r:container_t:s0: ... tcontext=system_u:object_r:proc_t:s0 
tclass=filesystem permissive=0

**Comment by ravenpride** [comment]
Hi, thank you for the report.

The Zimbra container needs to perform a few steps to spin up a Linux environment, one is to mount `/dev`, `/proc` and `/sys`. Your SELinux Policy seems to block this in a chrooted environment. I'm sorry, but I can't tell you how to configure the policy to get it working. On my system, I've SELinux disabled by default, so this did not occur, yet. You can try to start the docker container with `--security-opt label=disable` to disable SELinux for the Zimbra container only.

**Comment by Phil67ago** [comment]
Ok, I vill try that!

**Comment by ravenpride** [comment]
I assume the issue has been solved, so I'll close it. Please feel free to reopen it, if you need further support.
