### ISSUE TITLE
Conteneur Crashed

### ISSUE THREAD

**Issue by legolass73** [GriffinPlus/docker-zimbra#7]
my container just crashed, right after I accepted this line : " Use Zimbra's package repository [Y] "

then in the log file it appears that: 

Warning: apt-key output should not be parsed (stdout is not a terminal)
Importing Zimbra GPG key
ERROR: Unable to retrive Zimbra GPG key for package validation
Please fix system to allow normal package installation before proceeding

**Comment by ravenpride** [comment]
That indeed looks strange...
I'll spawn a fresh container and try it out.

**Comment by legolass73** [comment]
Do I have to reinstall him in full?
Because it crashed, I tried to revive the dockworker. He said, "Waiting for signals..."
 It took a long time to download it. Do you think deleting the folder will restart the install?

**Comment by ravenpride** [comment]
Yep, you have to use a fresh volume. It must not contain any files, otherwise the script will not use it to avoid destroying data.

**Comment by ravenpride** [comment]
@Rp70 contributed a fix (PR #8) that might solve your issue as well. Would you give it a try?

**Comment by jesuslas** [comment]
why not use the flag --hostname to zimbra and --domainname to my-domain.com.
this config the container with the zimbra in hostname and zimbra.my-domain.com in hostname --fqdn
but not working. I cant send email to external domain i dont know how change port 25 to 587 from webmail zimbra???
or i dont know what happen?

pliz help me with that no finishing my project

**Comment by ravenpride** [comment]
That seems to be some other issue. I'll create a new issue for it. Please see issue #9.

**Comment by ravenpride** [comment]
@legolass73 
Did you manage to get the container running? If yes, then I'll close  the issue. If no, please provide further information, so I can try to help you to track it down.

**Comment by ravenpride** [comment]
As you didn't provide any additional information to track it down, I'll close the issue now.

Please feel free to reopen it, if there is still something to discuss.
